Repository devugees/react-shopitme, pull requests merged in 2018-05, with the labels that each got.

#118 dropmenu wiring history,profile
  frontend/src/components/nav-bar/DropMenu.js
  frontend/src/components/nav-bar/Navbar.js
Labels: in progress

#119 Feature/fixmodals
  frontend/src/components/Modals/Login.js
  frontend/src/components/Modals/ResetPassword.js
  frontend/src/components/Modals/Sure.js
  frontend/src/components/Router/Router.js
  frontend/src/components/landing/Landing555.css
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/nav-bar/Navbar.js
Labels: in progress

#120 Hotfix/small fixes
  frontend/src/components/shopping-list-title/ShoppingListTitle.js
Labels: in progress

#121 Hotfix/small fixes
  frontend/src/components/shopping-list-title/ShoppingListTitle.js
Labels: in progress

#123 fix the router with navbar
  frontend/src/App.js
  frontend/src/components/Router/Router.js
  frontend/src/components/nav-bar/DropMenu.js
Labels: in progress

#126 Feature/aja xcall
  backend/server/config/passport.js
  backend/server/models/user.js
  backend/server/models/user2.js
  backend/server/routes/auth.js
  frontend/src/components/edit-user/EditUser.js
  frontend/src/components/edit-user/UserDetailsFields.js
  frontend/src/components/landing/Landing.js
  frontend/src/components/landing/Landing1.css
  frontend/src/components/landing/Landing1.js
  frontend/src/components/landing/Landing4.js
  frontend/src/components/landing/Landing5.css
  frontend/src/components/landing/Landing5.js
  frontend/src/components/master-components/UserDetails.js
  frontend/src/helpers/helpers.js
  frontend/src/pictures/button_man.png
  frontend/src/pictures/button_man.psd
  frontend/src/pictures/button_woman.png
  frontend/src/pictures/button_woman.psd
  frontend/src/pictures/landing.jpg
  frontend/src/pictures/landing1.jpg
  frontend/src/pictures/landing_lrg.jpg
  frontend/src/pictures/landing_mob.jpg
  frontend/src/pictures/landing_mob.png
  frontend/src/pictures/landing_mob.xcf
  frontend/src/pictures/lorder.jpg
  frontend/src/pictures/shopping_list.png
  frontend/src/pictures/triangle.jpg
Labels: question

#130 Name on user menu, logout to / and naming changes
  frontend/src/components/Modals/Login.js
  frontend/src/components/avatar/image.js
  frontend/src/components/nav-bar/Avatars.js
  frontend/src/components/nav-bar/DropMenu.js
  frontend/src/components/nav-bar/Navbar.js
  frontend/src/components/todo-list/TodoList.js
Labels: frontend1, question

#132 Feature/resetpassword
  backend/package-lock.json
  backend/package.json
  backend/server/models/user.js
  backend/server/routes/auth.js
  backend/server/routes/mailnotifier.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Modals/Login.js
  frontend/src/components/Modals/ResetPassword.js
  frontend/src/components/Router/Router.js
  frontend/src/components/master-components/NewPassord.js
  frontend/src/components/nav-bar/Navbar.js
Labels: in progress

#133 Feature/context api
  frontend/src/App.js
  frontend/src/components/Router/Router.js
  frontend/src/components/main-delivery-page/index.js
  frontend/src/components/master-components/AcceptedDelivery.js
  frontend/src/components/master-components/MainDeliveryPage.js
  frontend/src/components/nav-bar/Navbar.js
  frontend/src/fakeStore.js
Labels: in progress

#131 Feature/db
  backend/server/models/history.js
  backend/server/models/user.js
  backend/server/routes/auth.js
Labels: in progress

#134 Proxy made, all run in one terminal
  backend/server/models/user2.js
  frontend/package.json
  frontend/src/components/Modals/ResetPassword.js
  frontend/src/components/master-components/AcceptedDelivery.js
  frontend/src/components/master-components/NewPassord.js
  frontend/src/components/master-components/UserDetails.js
  frontend/src/components/nav-bar/Navbar.js
  frontend/src/fakeStore.js
  frontend/src/helpers/helpers.js
  frontend/yarn.lock
  package-lock.json
  package.json
  server/config/passport.js
  server/index.js
  server/models/history.js
  server/models/user.js
  server/routes/auth.js
  server/routes/mailnotifier.js
  server/routes/user.js
  yarn.lock
Labels: in progress

#143 changed user model so password is not required
  server/models/user.js
  server/routes/user.js
Labels: in progress

#140 Feature/db
  server/models/history.js
Labels: in progress

#147 Feature/locate order in map
  frontend/src/components/main-delivery-page/deliveryList.js
  frontend/src/components/main-delivery-page/index.js
  frontend/src/components/map/Map.js
  frontend/src/pictures/account.svg
  frontend/src/pictures/basket.svg
  frontend/src/pictures/home-map-marker.svg
  frontend/src/pictures/map-marker-radius.svg
  server/routes/user.js
Labels: in progress
