Repository devugees/react-shopitme, pull requests merged in 2018-06, with the labels that each got.

#148 Feature/create shopping list linked to server front end
  .gitignore
  frontend/package-lock.json
  frontend/src/components/Additional-Notes/Notes.js
  frontend/src/components/Details/Details.js
  frontend/src/components/Main.js
  frontend/src/components/Modals/Sure.js
  frontend/src/components/RatingStars.js
  frontend/src/components/Router/Router.js
  frontend/src/components/avatar/image.js
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/master-components/OrderDeliveryHistory.js
  frontend/src/components/middlewares/CreateShoppingListMiddleware.js
  frontend/src/components/shopping-list-title/ShoppingListTitle.js
  frontend/src/components/todo-list/TodoList.js
  frontend/src/fakeStore.js
  package-lock.json~Stashed changes
  package-lock.json~Updated upstream
  server/config/passport.js
  server/models/user.js
  server/routes/user.js
Labels: in progress

#162 Hotfix/fast improvements
  frontend/src/App.css
  frontend/src/components/Additional-Notes/Notes.js
  frontend/src/components/Additional-Notes/notes.css
  frontend/src/components/Details/Details.js
  frontend/src/components/Router/Router.js
  frontend/src/components/landing/Landing555.css
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/master-components/OrderDeliveryHistory.js
  frontend/src/components/nav-bar/DropMenu.js
  frontend/src/components/nav-bar/Navbar.css
  frontend/src/components/nav-bar/Navbar.js
  frontend/src/components/todo-list/TodoBoxOrdered.js
  frontend/src/components/todo-list/TodoList.js
  server/config/passport.js
  server/models/data.js
  server/routes/user.js
Labels: question

#164 Feature/authentication frontend
  .gitignore
  frontend/src/components/Modals/Login.js
  frontend/src/components/Router/Router.js
  frontend/src/components/landing/Landing.js
  frontend/src/components/nav-bar/Navbar.js
  frontend/src/components/privateRoute.js
  frontend/src/helpers/helpers.js
  package-lock.json~Updated upstream
  package.json
  server/models/data.js
  server/routes/user.js
  uploads/e275ca6bfbb06c0017cf4439e9c1c89a
  yarn.lock
Labels: in progress

#175 Feature/authentication frontend
  frontend/src/components/Router/Router.js
  server/routes/user.js
Labels: in progress

#179 Adapted Model, OrderID pushed to DB
  server/models/data.js
  server/models/user.js
  server/routes/user.js
Labels: in progress

#180 Feature/confirmation msg
  frontend/src/components/Router/Router.js
  frontend/src/components/confirmation-message/index.js
  frontend/src/components/master-components/CreateShoppingList.js
  server/routes/user.js
Labels: question

#181 Changed naming in create shopping list
  frontend/src/components/master-components/CreateShoppingList.js
Labels: question

#182 Change Filename to NewPassword
  frontend/src/components/Router/Router.js
  frontend/src/components/master-components/NewPassword.js
Labels: in progress

#183 Feature/not found
  frontend/public/index.html
  frontend/src/components/not-found/notFound.css
  frontend/src/components/not-found/notFound.js
Labels: question

#189 Now mobiles can login again
  frontend/src/components/Router/Router.js
  frontend/src/components/nav-bar/Navbar.js
  frontend/src/helpers/helpers.js
  server/routes/auth.js
  server/routes/user.js
Labels: Code Review

#188 Feature/not found2
  frontend/src/components/not-found/notFound.css
  frontend/src/components/not-found/notFound.js
  frontend/src/pictures/notfound.jpg
  frontend/src/pictures/notfound.png
Labels: Code Review, question

#196 Feature/adopt footer component
  frontend/src/components/Footer.js
  frontend/src/components/Router/Router.js
  frontend/src/components/footer/Footer.css
  frontend/src/components/footer/Footer.js
  frontend/src/helpers/helpers.js
Labels: in progress

#193 Hotfix/cleaning code1
  frontend/src/components/footer/Footer.js
Labels: Code Review

#194 all the menu text in one line
  frontend/src/components/nav-bar/Navbar.js
Labels: Code Review

#203 Fixed issue with mobile devices
  frontend/src/components/nav-bar/Navbar.js
Labels: Code Review, Do ASAP, bug

#201 Feature/history deliver
  frontend/src/components/Details/Details.js
  frontend/src/components/Modals/Login.js
  frontend/src/components/Modals/svg/facebook.svg
  frontend/src/components/main-delivery-page/index.js
  frontend/src/components/master-components/AcceptSingleDelivery.js
  frontend/src/components/master-components/AcceptedDelivery.js
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/order-delivery-history/index.js
  frontend/src/components/shopping-list-title/ShoppingListTitle.js
  frontend/src/components/show-delivery-details/ShowDeliveryDetails.js
  frontend/src/fakeStore.js
Labels: Code Review

#200 Feature/accept delivery
  frontend/src/components/main-delivery-page/index.js
  frontend/src/components/master-components/AcceptSingleDelivery.js
  frontend/src/components/master-components/MainDeliveryPage.js
  server/models/data.js
  server/routes/user.js
Labels: Code Review, question

#211 Hotfix/login popup error 186
  frontend/src/components/Modals/Login.js
  frontend/src/components/landing/Landing.js
  frontend/src/components/nav-bar/Navbar.js
Labels: Code Review

#218 Auto stash before merge of "develop" and "origin/develop"
  frontend/src/components/edit-user/UserDetailsFields.js
  frontend/src/components/master-components/UserDetails.js
Labels: in progress

#213 Avatar Image Updates in DeliveryOrderHistory after Avatar img update in UserDetails
  frontend/src/components/master-components/OrderDeliveryHistory.js
  uploads/5c635df617f40c1d4b9dc0bb396faefe
  uploads/c9c4f2052d2154baed24f418274b93d9
  uploads/dbb840d73ecf7010e9285200097ed087
  uploads/e809a8851fe1fd73994023d638047c21
Labels: Code Review

#212 added uploads folder to gitignore
  .gitignore
Labels: Code Review

#202 Feature/read user history db
  .gitignore
  frontend/src/components/RatingStars.js
  frontend/src/components/main-delivery-page/index.js
  frontend/src/components/master-components/AcceptSingleDelivery.js
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/master-components/OrderDeliveryHistory.js
  frontend/src/components/order-delivery-history/deliverHistory.js
  frontend/src/components/order-delivery-history/index.js
  frontend/src/components/order-delivery-history/orderHistory.js
  frontend/yarn.lock
  server/models/data.js
  server/routes/auth.js
  server/routes/user.js
  uploads/f12770de77c2c1f639a13af05b442be4
Labels: Code Review

#219 fixed curly bracket error
  frontend/src/components/master-components/OrderDeliveryHistory.js
Labels: in progress

#223 Auto stash before merge of "develop" and "origin/develop"
  frontend/src/components/map/Map.js
  server/models/user.js
Labels: in progress

#220 Fix arrow buttons css in delivery list
  frontend/src/components/main-delivery-page/deliveryList.js
  frontend/src/components/order-delivery-history/deliverHistory.js
  frontend/src/components/order-delivery-history/orderHistory.js
Labels: in progress

#228 Hotfix/geoposfix
  frontend/src/components/master-components/UserDetails.js
  server/routes/auth.js
Labels: in progress

#238 Hotfix/axios to crud
  frontend/package.json
  frontend/src/components/Modals/ResetPassword.js
  frontend/src/components/master-components/NewPassword.js
  server/routes/auth.js
Labels: in progress

#241 Hotfix/update shopping list
  frontend/src/components/avatar/ImageCropper.js
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/master-components/OrderDeliveryHistory.js
  frontend/src/components/order-delivery-history/orderHistory.js
  frontend/src/components/single-order-deliver-history/SingleDeliverHistory.js
  frontend/src/components/single-order-deliver-history/SingleOrderHistory.js
  server/routes/user.js
Labels: in progress

#240 Hotfix/orderinfo maindeliverypage
  frontend/src/components/Additional-Notes/Notes.js
  frontend/src/components/Details/Details.js
  frontend/src/components/master-components/CreateShoppingList.js
  server/models/data.js
  server/routes/user.js
Labels: in progress

#243 Hotfix/change order status to delivered
  frontend/src/components/master-components/AcceptedDelivery.js
  frontend/src/components/order-delivery-history/index.js
  server/routes/user.js
Labels: in progress

#245 fix bug in reset password
  frontend/src/components/master-components/NewPassword.js
Labels: in progress

#250 Hotfix/orderinfo maindeliverypage
  frontend/src/components/Additional-Notes/Notes.js
  frontend/src/components/Details/Details.js
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/shopping-list-title/ShoppingListTitle.js
  frontend/src/components/todo-list/TodoList.js
  server/models/data.js
  server/routes/user.js
Labels: Code Review

#251 Feature/show user pict on navbar
  frontend/src/components/nav-bar/DropMenu.js
  frontend/src/components/nav-bar/Navbar.css
  frontend/src/components/nav-bar/Navbar.js
  uploads/5eb84a7838fe5f63bbf8ff0d6cc989d0
  uploads/f499d3acf765e5a6e7fbda208c2df504
Labels: Code Review

#253 Image Fixed
  frontend/src/components/nav-bar/DropMenu.js
Labels: Code Review

#255 Hotfix/new app name
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/shopping.ico
  frontend/src/components/Footer.js
  frontend/src/components/footer/Footer.js
  frontend/src/components/master-components/OrderDeliveryHistory.js
  frontend/src/components/nav-bar/Navbar.js
  server/routes/auth.js
Labels: Code Review

#257 Hotfix/fix arrow buttons
  frontend/src/components/main-delivery-page/deliveryList.css
  frontend/src/components/main-delivery-page/deliveryList.js
  frontend/src/components/order-delivery-history/deliverHistory.js
  frontend/src/components/order-delivery-history/index.css
  frontend/src/components/order-delivery-history/orderHistory.js
Labels: in progress

#258 Hotfix/maindelivery page info
  frontend/src/components/main-delivery-page/deliveryList.js
  frontend/src/components/main-delivery-page/index.js
  frontend/src/components/master-components/AcceptSingleDelivery.js
  frontend/src/components/shopping-list-title/ShoppingListTitle.js
  frontend/src/components/show-delivery-details/ShowDeliveryDetails.js
Labels: Code Review

#261 feat: enforce mobile view, REVERT BEFORE RELEASE
  frontend/public/index.html
  frontend/src/components/landing/Landing.css
Labels: in progress

#265 Fixed no default avatar
  frontend/src/components/master-components/UserDetails.js
Labels: Code Review

#266 Hotfix/cleaning code 2
  frontend/src/components/Modals/ResetPassword.js
  frontend/src/components/avatar/ImageCropper.js
  frontend/src/components/main-delivery-page/index.js
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/master-components/OrderDeliveryHistory.js
  frontend/src/components/master-components/UserDetails.js
  frontend/src/pictures/notfound.jpg
  frontend/src/pictures/nyancat.jpg
  frontend/src/pictures/starGrey.jpg
  frontend/src/pictures/starGrey.png
  frontend/src/pictures/starRed.png
  frontend/src/pictures/starYellow.png
Labels: Code Review

#263 Hotfix/orderer icon mark shown in maindeliverypage
  frontend/src/components/main-delivery-page/index.js
Labels: Code Review

#268 Hotfix/history info
  frontend/src/components/master-components/AcceptSingleDelivery.js
  frontend/src/components/master-components/AcceptedDelivery.js
  frontend/src/components/order-delivery-history/deliverHistory.js
  frontend/src/components/order-delivery-history/orderHistory.js
  frontend/src/components/shopping-list-title/ShoppingListTitle.js
  frontend/src/components/single-order-deliver-history/SingleDeliverHistory.js
  frontend/src/components/single-order-deliver-history/SingleOrderHistory.js
  server/models/data.js
  server/routes/auth.js
  server/routes/user.js
Labels: Code Review

#269 .env mailgun => google account
  README.md
  package.json
  server/routes/auth.js
  server/routes/mailnotifier.js
Labels: in progress

#274 added 3 stars by default and related with DB
  frontend/src/components/master-components/OrderDeliveryHistory.js
  frontend/src/components/master-components/UserDetails.js
  server/models/user.js
Labels: Code Review

#275 randomly create a geopos arround DCI
  frontend/src/components/nav-bar/Navbar.js
  frontend/src/helpers/helpers.js
Labels: Code Review

#276 the last user details is hidden now
  frontend/src/components/edit-user/EditUser.js
  frontend/src/components/edit-user/UserDetailsFields.js
Labels: Code Review

#279 the the old profile pic is deleted from folder now
  server/routes/user.js
  uploads/0208793d99ea1ae479d9e418bceaa4f1
  uploads/04a7427f0e548035fe576b359f4b2552
  uploads/06ca9cd47d3f3b20faafb2fe6eb3b246
  uploads/0ed8ecb12cddc98f5cba11aedac03557
  uploads/25f69e2e9ceb8effd425142e428e2b73
  uploads/3e384a54439075cd6e3cb0b8a2ee5056
  uploads/4396d792b4d29cda5ddb10206671c147
  uploads/4c46a3a35d846b81e08310914a66702a
  uploads/4cc88004f1aa52718754d9a7b782390d
  uploads/4e89928edfec5b3ba9df8122aa2c21af
  uploads/5144b6c6e58f2899dff69ab51cdba916
  uploads/5c3fc7fc4a9f000f9c9deb3ab3201640
  uploads/5c635df617f40c1d4b9dc0bb396faefe
  uploads/5d66632557073f8b8e87fd74622b0594
  uploads/5eb84a7838fe5f63bbf8ff0d6cc989d0
  uploads/627ebdfed15362b32252a42a7b8e76ac
  uploads/6e9289025b38e031f32deb21c6c6f833
  uploads/6eeaace802f59e8784e8ab7aa275a876
  uploads/736c6ebb32456a190174fc53f725cd15
  uploads/7e8281d497fa78ecf8765fa35ac8c235
  uploads/8273d4142c29bb0704e95ddb8d70e37c
  uploads/839e1397d93de446361754b257b840e6
  uploads/84ee6b40756bfaec4f169dfcc230845e
  uploads/9015ee8a4db35deacf0134e4b16c3905
  uploads/9b3df30697edeb96a08292ffdb5d93a1
  uploads/a808ab296bf9c9a0cf0e3fbb88493535
  uploads/b08776413455a8cca1bd84ce13fcd24f
  uploads/b324a2633498ecdc0c0ac2604bd86b53
  uploads/b3567736f4c283847184e53b4d319036
  uploads/c9c4f2052d2154baed24f418274b93d9
  uploads/d6d56378cbbc6afe2623ebfb7c705798
  uploads/dbb840d73ecf7010e9285200097ed087
  uploads/de01406821cdf8c0d885a93db43ecdb6
  uploads/e275ca6bfbb06c0017cf4439e9c1c89a
  uploads/e809a8851fe1fd73994023d638047c21
  uploads/eb1dec307ca2185954a9d4e976faf611
  uploads/f12770de77c2c1f639a13af05b442be4
  uploads/f499d3acf765e5a6e7fbda208c2df504
  uploads/f689ed0623a20198acbd5343171c689b
Labels: in progress

#286 the delivered orders are hidden from main delivery pag now
  frontend/src/components/main-delivery-page/index.js
Labels: in progress

#288 Hotfix/typo order detials
  frontend/src/components/show-delivery-details/ShowDeliveryDetails.js
Labels: Code Review

#289 Feature/redirection
  .env.example
  frontend/src/components/Router/Router.js
  frontend/src/components/master-components/AcceptSingleDelivery.js
  frontend/src/components/master-components/AcceptedDelivery.js
  frontend/src/components/master-components/CreateShoppingList.js
  frontend/src/components/master-components/UserDetails.js
  frontend/src/components/order-delivery-history/index.js
Labels: in progress

#292 Hotfix/cleanthe console
  frontend/src/components/todo-list/TodoList.js
  server/routes/auth.js
  server/routes/user.js
Labels: in progress

#291 make the wall menu item clickable
  frontend/src/components/nav-bar/DropMenu.js
Labels: in progress
